<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260319141741 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE department (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE employee (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(10) NOT NULL, role VARCHAR(10) NOT NULL, login_token VARCHAR(6) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, department_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5D9F75A1AE80F5DF ON employee (department_id)');
        $this->addSql('CREATE TABLE guest (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, room_number VARCHAR(10) NOT NULL, session_token VARCHAR(6) NOT NULL, checked_in_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, check_out_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(20) NOT NULL, description VARCHAR(255) NOT NULL, category VARCHAR(10) NOT NULL, is_schedulable BOOLEAN NOT NULL, available_from VARCHAR(5) DEFAULT NULL, available_to VARCHAR(5) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, department_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E19D9AD2AE80F5DF ON service (department_id)');
        $this->addSql('CREATE TABLE service_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, room_number VARCHAR(10) NOT NULL, created_by INT DEFAULT NULL, schedule_at TIME(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, guest_id INT NOT NULL, employee_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F413DD039A4AA658 ON service_request (guest_id)');
        $this->addSql('CREATE INDEX IDX_F413DD038C03F15C ON service_request (employee_id)');
        $this->addSql('CREATE TABLE service_request_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, previous_status VARCHAR(10) DEFAULT NULL, new_status VARCHAR(10) NOT NULL, changed_by INT DEFAULT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, service_request_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2F9F72F8D42F8111 ON service_request_history (service_request_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A1AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE service_request ADD CONSTRAINT FK_F413DD039A4AA658 FOREIGN KEY (guest_id) REFERENCES guest (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE service_request ADD CONSTRAINT FK_F413DD038C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE service_request_history ADD CONSTRAINT FK_2F9F72F8D42F8111 FOREIGN KEY (service_request_id) REFERENCES service_request (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE employee DROP CONSTRAINT FK_5D9F75A1AE80F5DF');
        $this->addSql('ALTER TABLE service DROP CONSTRAINT FK_E19D9AD2AE80F5DF');
        $this->addSql('ALTER TABLE service_request DROP CONSTRAINT FK_F413DD039A4AA658');
        $this->addSql('ALTER TABLE service_request DROP CONSTRAINT FK_F413DD038C03F15C');
        $this->addSql('ALTER TABLE service_request_history DROP CONSTRAINT FK_2F9F72F8D42F8111');
        $this->addSql('DROP TABLE department');
        $this->addSql('DROP TABLE employee');
        $this->addSql('DROP TABLE guest');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE service_request');
        $this->addSql('DROP TABLE service_request_history');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
